---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian8_local
    driver:
        box: debian8_local
        box_url: "http://apache.pitux.ovh/data/vagrant/debian8_local.box"

suites:
  - name: default
    run_list:
      - recipe[platform_qemu::default]
    attributes:
    driver:
      network:
        - [ 'private_network', { ip: '192.168.24.11' } ]
