---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian8_local
    driver:
        box: debian8_local

suites:
  - name: default
    run_list:
      - recipe[platform_qemu::default]
    attributes:
    driver:
      network:
        - [ 'private_network', { ip: '192.168.42.11' } ]
      synced_folders:
        - ["data/", "/home/vagrant/data"]
