name 'platform_qemu'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures chef-platform_qemu'
long_description 'Installs/Configures chef-platform_qemu'
version '0.1.1'
